#!/bin/sh

case "$1" in
	start)
		/home/MX5-GNC &> /var/log/gaincontrolsoftware.log &
		echo `pgrep MX5-GNC` > /var/run/gaincontrolsoftware.pid
		sleep 1
		;;
	stop)
		killall MX5-GNC
		rm /var/run/gaincontrolsoftware.pid
		;;
	*)
		echo "usage: $0 [start|stop]"
		exit 1
		;;
esac

