#!/bin/sh

case "$1" in
	start)
		/usr/jre/bin/java -jar /home/IOMaster.jar &> /var/log/iomaster.log &
		echo `pgrep java` > /var/run/iomaster.pid
		sleep 1
		;;
	stop)
		killall java
		rm /var/run/iomaster.pid
		;;
	*)
		echo "usage: $0 [start|stop]"
		exit 1
		;;
esac

